import os
import razorpay
import hmac
import hashlib
from typing import Dict, Any

RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID", "rzp_test_placeholder_key")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET", "rzp_test_placeholder_secret")
RAZORPAY_WEBHOOK_SECRET = os.getenv("RAZORPAY_WEBHOOK_SECRET", "")

def is_mock_mode_active() -> bool:
    """
    Returns True if valid Razorpay API keys are not supplied, defaulting to a mock transaction mode.
    """
    return (
        not RAZORPAY_KEY_ID 
        or not RAZORPAY_KEY_SECRET 
        or RAZORPAY_KEY_ID.startswith("rzp_test_placeholder")
    )

class RazorpayPaymentGateway:
    """
    Adapter that communicates with Razorpay APIs for order processing and payment verification.
    """
    def __init__(self) -> None:
        if not is_mock_mode_active():
            self.razorpay_client = razorpay.Client(auth=(RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET))
        else:
            self.razorpay_client = None

    def create_payment_order(self, amount_in_inr: float, order_reference_identifier: str) -> Dict[str, Any]:
        """
        Creates an order on Razorpay and returns the transaction details.
        """
        amount_in_paise = int(amount_in_inr * 100)

        if is_mock_mode_active():
            # Simulated order for local development
            import uuid
            mock_order_identifier = f"order_mock_{uuid.uuid4().hex[:12]}"
            return {
                "id": mock_order_identifier,
                "amount": amount_in_paise,
                "currency": "INR",
                "receipt": order_reference_identifier,
                "status": "created"
            }

        try:
            order_parameters = {
                "amount": amount_in_paise,
                "currency": "INR",
                "receipt": order_reference_identifier,
                "payment_capture": 1
            }
            razorpay_order = self.razorpay_client.order.create(data=order_parameters)
            return razorpay_order
        except Exception as razorpay_exception:
            raise RuntimeError(
                f"Failed to create transaction order via Razorpay API: {str(razorpay_exception)}"
            ) from razorpay_exception

    def verify_payment_signature(
        self, 
        razorpay_order_id: str, 
        razorpay_payment_id: str, 
        razorpay_signature: str
    ) -> bool:
        """
        Verifies the HMAC-SHA256 signature generated by Razorpay.
        """
        if is_mock_mode_active():
            # Allow mock signatures or 'mock' token in development
            return (
                razorpay_signature.startswith("mock_signature") 
                or razorpay_signature == "mock"
            )

        try:
            signature_base_string = f"{razorpay_order_id}|{razorpay_payment_id}"
            computed_signature = hmac.new(
                bytes(RAZORPAY_KEY_SECRET, "utf-8"),
                msg=bytes(signature_base_string, "utf-8"),
                digestmod=hashlib.sha256
            ).hexdigest()

            return hmac.compare_digest(computed_signature, razorpay_signature)
        except Exception:
            return False

    def verify_webhook_signature(
        self,
        request_body_bytes: bytes,
        webhook_signature_header: str
    ) -> bool:
        """
        Verifies the HMAC-SHA256 signature sent by Razorpay in the X-Razorpay-Signature
        header of webhook POST requests. Uses the RAZORPAY_WEBHOOK_SECRET for computation.
        """
        if not RAZORPAY_WEBHOOK_SECRET:
            return False

        try:
            computed_signature = hmac.new(
                key=bytes(RAZORPAY_WEBHOOK_SECRET, "utf-8"),
                msg=request_body_bytes,
                digestmod=hashlib.sha256
            ).hexdigest()

            return hmac.compare_digest(computed_signature, webhook_signature_header)
        except Exception:
            return False

